### ISSUE TITLE
Arrow keys control both the map and focused file

### ISSUE THREAD

**Issue by pdonias** [gpxstudio/gpx.studio#148] opened 2024-11-05 10:07 UTC
Steps to reproduce:
- Open at least 2 files
- Click on a file to focus it
- Click on the map
- Press left and rigth arrows

Result: the map moves left and right *and* the focused file changes. I don't think that's the intended behaviour.

**Comment by vcoppe** [comment] 2024-11-12 21:41
Duplicate of #44 .

**Closed** 2024-11-12 21:41 UTC
